# Generated by Django 4.0.5 on 2022-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('info_count', models.IntegerField()),
                ('errors_count', models.IntegerField()),
                ('pre_legend', models.IntegerField()),
                ('warning', models.IntegerField()),
                ('paired_b', models.IntegerField()),
                ('legend', models.IntegerField()),
                ('lower_b', models.IntegerField()),
                ('repeat_legend', models.IntegerField()),
                ('upper_a', models.IntegerField()),
                ('lower_a', models.IntegerField()),
                ('paired_a', models.IntegerField()),
            ],
        ),
    ]
